### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hqy2000** [nfls/nflsers#2]
- [x] Use QLPreviewController on file previewing

- [x] Use UITableView to show identity status

- [x] Disable spelling check on certain circumstances

- [x] Get startup pictures from server

- [x] Add count for system messages

- [x] Show alumni posts from markdown

- [x] Show video list in the media section

- [x] Add change password etc section
